use memsw
ThinkSpiritLab/Heng-Core pull request #3
Opened 2021-11-16 13:41 UTC by flaryer

use memsw and some small fix...

2021-11-16 16:33 UTC, A0nameless0man requested changes

2021-11-16 16:33 UTC, A0nameless0man commented on .vscode/c_cpp_properties.json
> +    "configurations": [
加个 gitignore 之后，用git commit --amend修正一下这个多余文件吧

2021-11-16 16:33 UTC, A0nameless0man commented on .vscode/c_cpp_properties.json
> +    "configurations": [
其他的ok

2021-11-16 16:40 UTC, flaryer commented on .vscode/c_cpp_properties.json
> +    "configurations": [
vscode不配c++版本，识别不了filesystem

2021-11-16 16:46 UTC, flaryer commented on .vscode/c_cpp_properties.json
> +    "configurations": [
不过.vscode确实不该放进git

2021-11-18 15:14 UTC, A0nameless0man approved these changes

2021-11-19 06:06 UTC, merged